package com.dandi.nyummy.common.presentation.ui.token

import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.dandi.nyummy.common.presentation.ui.color.DesignSystemSemanticColors
import com.dandi.nyummy.common.presentation.ui.color.DesignSystemBackgroundColors
import com.dandi.nyummy.common.presentation.ui.color.DesignSystemContentColors
import com.dandi.nyummy.common.presentation.ui.color.DesignSystemBorderColors
import com.dandi.nyummy.common.presentation.ui.color.DesignSystemAssetColors
import com.dandi.nyummy.common.presentation.ui.color.DesignSystemDataColors
import com.dandi.nyummy.common.presentation.ui.theme.DesignSystemEffects
import com.dandi.nyummy.common.presentation.ui.theme.DesignSystemElevation
import com.dandi.nyummy.common.presentation.ui.theme.DesignSystemLayout
import com.dandi.nyummy.common.presentation.ui.theme.DesignSystemRadius
import com.dandi.nyummy.common.presentation.ui.theme.DesignSystemShadow
import com.dandi.nyummy.common.presentation.ui.theme.DesignSystemShape
import com.dandi.nyummy.common.presentation.ui.theme.DesignSystemSize
import com.dandi.nyummy.common.presentation.ui.theme.DesignSystemSpacing
import com.dandi.nyummy.common.presentation.ui.typo.ArchiStaticTypeScale
import com.dandi.nyummy.common.presentation.ui.typo.DesignSystemTypeScale
import com.dandi.nyummy.common.presentation.ui.typo.fredokaNumberFont
import com.dandi.nyummy.common.presentation.ui.typo.gowunDodumVoiceFont
import com.dandi.nyummy.common.presentation.ui.typo.juaDisplayFont
import com.dandi.nyummy.common.presentation.ui.typo.notoSansKrTextFont

// Generated from Nyummy Figma Design System v1.0.0-rc.3 (Light-only).
// UI code consumes semantic/theme roles; palette values remain internal.

// FIGMA-TOKEN-INJECTION-POINT: palette
@Suppress("Unused")
internal enum class ArchiPaletteColors(val colorValue: Color) {
    // Kept for source compatibility with the original Android architecture template.
    Black(Color(0xFF000000)),
    Gray300(Color(0xFF222222)),
    Gray400(Color(0xFF444444)),
    Gray500(Color(0xFF888888)),
    Gray600(Color(0xFFC4C4C4)),
    Gray700(Color(0xFFDDDDDD)),
    Gray800(Color(0xFFE6E6E6)),
    Gray900(Color(0xFFF7F7F7)),
    White(Color(0xFFFFFFFF)),
    Blue400(Color(0xFF465179)),
    Red(Color(0xFFFF0000)),

    Apricot300(Color(0xFFFFA870)),
    Apricot350(Color(0xFFF4A261)),
    Apricot400(Color(0xFFFF8A45)),
    Apricot50(Color(0xFFFFF2E9)),
    Apricot60(Color(0xFFFFF7EA)),
    Apricot600(Color(0xFFD68B3C)),
    Apricot75(Color(0xFFFFF4E8)),
    Apricot800(Color(0xFF7A2B08)),
    Berry50(Color(0xFFFFF0F2)),
    Berry500(Color(0xFFD94062)),
    Berry600(Color(0xFFB9294D)),
    Berry700(Color(0xFF8F1E3A)),
    Berry900(Color(0xFF3C1E1E)),
    BrandGoogleBlue(Color(0xFF4285F4)),
    BrandGoogleGreen(Color(0xFF34A853)),
    BrandGoogleRed(Color(0xFFEA4335)),
    BrandGoogleYellow(Color(0xFFFBBC05)),
    Brick500(Color(0xFFB84848)),
    Brick600(Color(0xFFB84D4D)),
    Clay50(Color(0xFFFDEFE7)),
    Clay500(Color(0xFFC9783C)),
    Clay600(Color(0xFFA8662D)),
    Clay700(Color(0xFFA85F2E)),
    Clay800(Color(0xFFA44928)),
    Cocoa100(Color(0xFFEFE4DF)),
    Cocoa200(Color(0xFFD9C6BE)),
    Cocoa300(Color(0xFFB9A096)),
    Cocoa50(Color(0xFFF8F2EF)),
    Cocoa500(Color(0xFF73594F)),
    Cocoa575(Color(0xFF5A4A40)),
    Cocoa600(Color(0xFF594238)),
    Cocoa700(Color(0xFF704218)),
    Cocoa800(Color(0xFF33221B)),
    Cocoa900(Color(0xFF241610)),
    Coral500(Color(0xFFE8855C)),
    Coral700(Color(0xFFA65331)),
    Cream100(Color(0xFFFFF8F2)),
    Cream200(Color(0xFFFCEDE2)),
    Cream25(Color(0xFFFFFBF5)),
    Cream250(Color(0xFFF0E0CC)),
    Cream300(Color(0xFFF3DACB)),
    Cream50(Color(0xFFFFFDFC)),
    Evergreen100(Color(0xFFDDE7DE)),
    Evergreen125(Color(0xFFDCE8DE)),
    Evergreen200(Color(0xFFB7CFBC)),
    Evergreen25(Color(0xFFF7FBF7)),
    Evergreen250(Color(0xFFAFC9B5)),
    Evergreen300(Color(0xFF97928C)),
    Evergreen400(Color(0xFF758079)),
    Evergreen410(Color(0xFF757F79)),
    Evergreen425(Color(0xFF718078)),
    Evergreen450(Color(0xFF6F7972)),
    Evergreen50(Color(0xFFEEF5EE)),
    Evergreen500(Color(0xFF6B766F)),
    Evergreen55(Color(0xFFEDF4EE)),
    Evergreen550(Color(0xFF6A756D)),
    Evergreen60(Color(0xFFEAF3EB)),
    Evergreen600(Color(0xFF5F7065)),
    Evergreen650(Color(0xFF58735F)),
    Evergreen700(Color(0xFF547A61)),
    Evergreen725(Color(0xFF5E765F)),
    Evergreen740(Color(0xFF4F7762)),
    Evergreen75(Color(0xFFE6EEE7)),
    Evergreen750(Color(0xFF4F765A)),
    Evergreen800(Color(0xFF4E6153)),
    Evergreen900(Color(0xFF30372F)),
    Evergreen950(Color(0xFF28352C)),
    ExtendedApricotTone97Chroma100(Color(0xFFFFF7E9)),
    ExtendedBerryTone90(Color(0xFFFBDDD9)),
    ExtendedClayTone95(Color(0xFFF4F0EF)),
    ExtendedCocoaTone87(Color(0xFFE8D9C2)),
    ExtendedCocoaTone95(Color(0xFFF2F1EE)),
    ExtendedCoralTone58(Color(0xFFC9793F)),
    ExtendedCoralTone96(Color(0xFFFFF1E7)),
    ExtendedEvergreenTone45Alpha18(Color(0x2E55705C)),
    ExtendedEvergreenTone90(Color(0xFFD8E6DA)),
    ExtendedEvergreenTone90Chroma15(Color(0xFFDCE4DE)),
    ExtendedEvergreenTone90Chroma15Hue143(Color(0xFFDCE4DF)),
    ExtendedEvergreenTone95Chroma15(Color(0xFFEEF3EF)),
    ExtendedEvergreenTone95Chroma25(Color(0xFFEAF2EB)),
    ExtendedInkTone15Alpha14(Color(0x242B241A)),
    ExtendedInkTone20Alpha13(Color(0x2124342C)),
    ExtendedInkTone20Alpha6(Color(0x0F263329)),
    ExtendedInkTone36Alpha18(Color(0x2E6B4F3D)),
    ExtendedInkTone40(Color(0xFF45664F)),
    Gold400(Color(0xFFEBAA27)),
    Gold50(Color(0xFFFFF9E6)),
    Gold500(Color(0xFFC88614)),
    Gold600(Color(0xFF9F650D)),
    Gold700(Color(0xFF7B4B0D)),
    Ink900(Color(0xFF2B3731)),
    Ink950(Color(0xFF28332D)),
    Ivory25(Color(0xFFFFFDF9)),
    Ivory30(Color(0xFFFFFDF8)),
    Linen100(Color(0xFFFBF8F2)),
    Linen20(Color(0xFFF7FAF7)),
    Linen25(Color(0xFFFAFBF8)),
    Linen50(Color(0xFFFAFAF6)),
    MascotCoral(Color(0xFFFF7D5C)),
    MascotCoralDeep(Color(0xFFE85F43)),
    MascotCream(Color(0xFFF9DFA9)),
    MascotCreamHighlight(Color(0xFFFFF1C9)),
    MascotInk(Color(0xFF432516)),
    MascotShadow(Color(0xFFD4A66C)),
    Neutral50(Color(0xFFF5F5F5)),
    NeutralBlack(Color(0xFF000000)),
    NeutralWhite(Color(0xFFFFFFFF)),
    OverlayCocoa12(Color(0x1F33221B)),
    OverlayCocoa18(Color(0x2E33221B)),
    OverlayCocoa22(Color(0x3833221B)),
    OverlayCocoa40(Color(0x66170D09)),
    PixelOutline(Color(0xFF7A4A2B)),
    PixelShadow(Color(0xFFC69863)),
    RoomFloor(Color(0xFFF1D3B4)),
    RoomWall(Color(0xFFFFF8EE)),
    RoomWindowSky(Color(0xFFDFF2FF)),
    Rose50(Color(0xFFFFF0EE)),
    Rose600(Color(0xFFA75E66)),
    Sage100(Color(0xFFDEE8E1)),
    Sage150(Color(0xFFD7E3DA)),
    Sage200(Color(0xFFC7DECC)),
    Sage400(Color(0xFF86A78D)),
    Sage425(Color(0xFF85A68C)),
    Sage450(Color(0xFF578C66)),
    Sage50(Color(0xFFF1F8EF)),
    Sage500(Color(0xFF4E8C46)),
    Sage600(Color(0xFF628C6B)),
    Sage700(Color(0xFF2F572B)),
    ShadowCocoa10(Color(0x1A6B5646)),
    Sky400(Color(0xFF54779A)),
    Sky50(Color(0xFFEFF7FF)),
    Sky500(Color(0xFF2B8BE8)),
    Sky600(Color(0xFF6B91C9)),
    Sky700(Color(0xFF1C589A)),
    Sky75(Color(0xFFEEF3F8)),
    Stone100(Color(0xFFF1ECE5)),
    Stone200(Color(0xFFE7E1D8)),
    Stone400(Color(0xFF7B827E)),
}

// FIGMA-TOKEN-INJECTION-POINT: semantic-colors
val DefaultDesignSystemColor = DesignSystemSemanticColors(
    background = DesignSystemBackgroundColors(
        bgDefaultLevel0 = ArchiPaletteColors.Cream100.colorValue,
        bgCanvasAlt = ArchiPaletteColors.Cream50.colorValue,
        bgDefaultLevel1 = ArchiPaletteColors.NeutralWhite.colorValue,
        bgSurfaceSubtle = ArchiPaletteColors.Cream50.colorValue,
        bgDefaultLevel2 = ArchiPaletteColors.Cream200.colorValue,
        bgSurfaceStrong = ArchiPaletteColors.Cocoa50.colorValue,
        bgSurfaceInverse = ArchiPaletteColors.Cocoa900.colorValue,
        bgBrandDefault = ArchiPaletteColors.Apricot400.colorValue,
        bgBrandSoft = ArchiPaletteColors.Apricot50.colorValue,
        bgSuccessSoft = ArchiPaletteColors.Sage50.colorValue,
        bgSuccessDefault = ArchiPaletteColors.Sage500.colorValue,
        bgInfoSoft = ArchiPaletteColors.Sky50.colorValue,
        bgInfoDefault = ArchiPaletteColors.Sky600.colorValue,
        bgWarningSoft = ArchiPaletteColors.Gold50.colorValue,
        bgWarningDefault = ArchiPaletteColors.Gold400.colorValue,
        bgDangerSoft = ArchiPaletteColors.Berry50.colorValue,
        bgDangerDefault = ArchiPaletteColors.Berry600.colorValue,
        bgProgressTrack = ArchiPaletteColors.Cocoa100.colorValue,
        bgActionPrimaryDefault = ArchiPaletteColors.Evergreen700.colorValue,
        bgActionPrimaryPressed = ArchiPaletteColors.ExtendedInkTone40.colorValue,
        bgNavigationFloating = ArchiPaletteColors.Cream25.colorValue,
        bgNavigationFullWidth = ArchiPaletteColors.NeutralWhite.colorValue,
        bgActionSecondaryDefault = ArchiPaletteColors.Linen20.colorValue,
        bgSurfaceIvory = ArchiPaletteColors.Ivory25.colorValue,
        bgScrimModal = ArchiPaletteColors.OverlayCocoa12.colorValue,
        bgScrimDefault = ArchiPaletteColors.OverlayCocoa40.colorValue,
        bgStatusPositive = ArchiPaletteColors.Sage400.colorValue,
        bgSelectionPrimary = ArchiPaletteColors.Sage400.colorValue,
        bgActionPrimaryDisabled = ArchiPaletteColors.ExtendedEvergreenTone90Chroma15.colorValue,
        bgActionSecondaryPressed = ArchiPaletteColors.Evergreen55.colorValue,
        bgActionSecondaryDisabled = ArchiPaletteColors.ExtendedCocoaTone95.colorValue,
        bgActionDangerDefault = ArchiPaletteColors.Rose50.colorValue,
        bgActionDangerPressed = ArchiPaletteColors.ExtendedBerryTone90.colorValue,
        bgActionDangerDisabled = ArchiPaletteColors.ExtendedClayTone95.colorValue,
        bgActionRewardDefault = ArchiPaletteColors.MascotCoral.colorValue,
        bgActionRewardPressed = ArchiPaletteColors.MascotCoralDeep.colorValue,
        bgInputDefault = ArchiPaletteColors.NeutralWhite.colorValue,
        bgInputDisabled = ArchiPaletteColors.ExtendedCocoaTone95.colorValue,
        bgSurfaceControl = ArchiPaletteColors.Cream25.colorValue,
        bgSurfaceCardSubtle = ArchiPaletteColors.Evergreen25.colorValue,
        bgStatusProcessing = ArchiPaletteColors.Evergreen50.colorValue,
        bgStatusWarning = ArchiPaletteColors.Clay50.colorValue,
        bgCalendarSelected = ArchiPaletteColors.Evergreen55.colorValue,
        bgMealPhoto = ArchiPaletteColors.ExtendedEvergreenTone95Chroma15.colorValue,
        bgProgressNutritionTrack = ArchiPaletteColors.ExtendedEvergreenTone95Chroma25.colorValue,
        bgCoachBubble = ArchiPaletteColors.ExtendedApricotTone97Chroma100.colorValue,
        bgSheetHandle = ArchiPaletteColors.ExtendedEvergreenTone90Chroma15Hue143.colorValue,
    ),
    content = DesignSystemContentColors(
        contentDefaultLevel0 = ArchiPaletteColors.Cocoa900.colorValue,
        contentDefaultLevel1 = ArchiPaletteColors.Cocoa600.colorValue,
        contentDefaultLevel2 = ArchiPaletteColors.Cocoa500.colorValue,
        contentDefaultLevel3 = ArchiPaletteColors.Cocoa300.colorValue,
        contentInverseDefault = ArchiPaletteColors.NeutralWhite.colorValue,
        contentAccent = ArchiPaletteColors.Apricot800.colorValue,
        contentSuccess = ArchiPaletteColors.Sage700.colorValue,
        contentInfo = ArchiPaletteColors.Sky700.colorValue,
        contentWarning = ArchiPaletteColors.Gold700.colorValue,
        contentError = ArchiPaletteColors.Berry700.colorValue,
        contentIconLevel0 = ArchiPaletteColors.Cocoa800.colorValue,
        contentIconLevel1 = ArchiPaletteColors.Cocoa500.colorValue,
        contentIconSuccess = ArchiPaletteColors.Sage600.colorValue,
        contentIconInfo = ArchiPaletteColors.Sky600.colorValue,
        contentIconWarning = ArchiPaletteColors.Gold600.colorValue,
        contentIconDanger = ArchiPaletteColors.Berry600.colorValue,
        contentActionPrimary = ArchiPaletteColors.NeutralWhite.colorValue,
        contentAccentSage = ArchiPaletteColors.Sage700.colorValue,
        contentAccentCoral = ArchiPaletteColors.Coral700.colorValue,
        contentActionDisabled = ArchiPaletteColors.Evergreen800.colorValue,
        contentActionSecondary = ArchiPaletteColors.ExtendedInkTone40.colorValue,
        contentActionSecondaryDisabled = ArchiPaletteColors.Evergreen800.colorValue,
        contentActionDanger = ArchiPaletteColors.Berry700.colorValue,
        contentActionDangerDisabled = ArchiPaletteColors.Berry700.colorValue,
        contentActionReward = ArchiPaletteColors.Cocoa900.colorValue,
        contentInputValue = ArchiPaletteColors.Evergreen950.colorValue,
        contentInputPlaceholder = ArchiPaletteColors.Evergreen500.colorValue,
        contentInputDisabled = ArchiPaletteColors.Evergreen800.colorValue,
        contentCalendarAdjacentMonth = ArchiPaletteColors.Evergreen450.colorValue,
        contentCalendarWeekday = ArchiPaletteColors.Evergreen550.colorValue,
        contentCalendarAction = ArchiPaletteColors.Evergreen650.colorValue,
        contentCalendarSaturday = ArchiPaletteColors.Evergreen700.colorValue,
        contentCalendarSunday = ArchiPaletteColors.Brick600.colorValue,
        contentStatusProcessing = ArchiPaletteColors.Evergreen750.colorValue,
        contentStatusSupporting = ArchiPaletteColors.Evergreen800.colorValue,
        contentStatusWarning = ArchiPaletteColors.Clay800.colorValue,
        contentNutritionLabel = ArchiPaletteColors.Evergreen800.colorValue,
        contentCalendarSelected = ArchiPaletteColors.Evergreen700.colorValue,
        contentCalendarDate = ArchiPaletteColors.Evergreen950.colorValue,
        contentEconomyBalance = ArchiPaletteColors.Apricot800.colorValue,
        contentSelectionPrimary = ArchiPaletteColors.Evergreen900.colorValue,
    ),
    border = DesignSystemBorderColors(
        borderDefaultLevel1 = ArchiPaletteColors.Cream300.colorValue,
        borderDefaultLevel0 = ArchiPaletteColors.Cocoa100.colorValue,
        borderBrandDefault = ArchiPaletteColors.Apricot300.colorValue,
        borderSuccessDefault = ArchiPaletteColors.Sage500.colorValue,
        borderInfoDefault = ArchiPaletteColors.Sky500.colorValue,
        borderWarningDefault = ArchiPaletteColors.Gold500.colorValue,
        borderDangerDefault = ArchiPaletteColors.Berry500.colorValue,
        borderDefaultLevel2 = ArchiPaletteColors.Cream200.colorValue,
        borderNavigationDefault = ArchiPaletteColors.Cream250.colorValue,
        borderNavigationFullWidthDivider = ArchiPaletteColors.Sage100.colorValue,
        borderSageSoft = ArchiPaletteColors.Sage200.colorValue,
        borderInputFocused = ArchiPaletteColors.Sage400.colorValue,
        borderSelectionPrimary = ArchiPaletteColors.Sage400.colorValue,
        borderActionSecondary = ArchiPaletteColors.ExtendedEvergreenTone90.colorValue,
        borderInputDefault = ArchiPaletteColors.Stone200.colorValue,
        borderInputError = ArchiPaletteColors.Brick500.colorValue,
        borderCalendarGrid = ArchiPaletteColors.Stone100.colorValue,
        borderCalendarOutline = ArchiPaletteColors.Stone200.colorValue,
        borderCardSubtle = ArchiPaletteColors.Stone200.colorValue,
        borderMealRow = ArchiPaletteColors.Evergreen100.colorValue,
        borderNutrition = ArchiPaletteColors.Evergreen125.colorValue,
        borderStatusProcessing = ArchiPaletteColors.Evergreen250.colorValue,
        borderCalendarSelected = ArchiPaletteColors.Evergreen700.colorValue,
        borderMealPhoto = ArchiPaletteColors.ExtendedEvergreenTone90.colorValue,
        borderCoachBubble = ArchiPaletteColors.ExtendedCocoaTone87.colorValue,
    ),
    asset = DesignSystemAssetColors(
        assetCharacterBody = ArchiPaletteColors.MascotCream.colorValue,
        assetCharacterHighlight = ArchiPaletteColors.MascotCreamHighlight.colorValue,
        assetCharacterAccent = ArchiPaletteColors.MascotCoral.colorValue,
        assetCharacterInk = ArchiPaletteColors.MascotInk.colorValue,
        assetCharacterShadow = ArchiPaletteColors.MascotShadow.colorValue,
        assetSceneRoomWall = ArchiPaletteColors.RoomWall.colorValue,
        assetSceneRoomFloor = ArchiPaletteColors.RoomFloor.colorValue,
        assetSceneWindowSky = ArchiPaletteColors.RoomWindowSky.colorValue,
        assetScenePixelOutline = ArchiPaletteColors.PixelOutline.colorValue,
        assetScenePixelShadow = ArchiPaletteColors.PixelShadow.colorValue,
    ),
    data = DesignSystemDataColors(
        dataNutrientCalorie = ArchiPaletteColors.MascotCoral.colorValue,
        dataNutrientCarbohydrate = ArchiPaletteColors.Gold500.colorValue,
        dataNutrientProtein = ArchiPaletteColors.Sage500.colorValue,
        dataNutrientFat = ArchiPaletteColors.Sky500.colorValue,
        dataEvaluationPositive = ArchiPaletteColors.Sage500.colorValue,
        dataEvaluationNegative = ArchiPaletteColors.Berry500.colorValue,
        dataEvaluationUnrecorded = ArchiPaletteColors.Cocoa200.colorValue,
        dataProgressDefault = ArchiPaletteColors.Sage400.colorValue,
        dataTrendPrimary = ArchiPaletteColors.Sage400.colorValue,
        dataCalendarRecorded = ArchiPaletteColors.Sage400.colorValue,
        dataCalendarToday = ArchiPaletteColors.Evergreen700.colorValue,
        dataEconomyCoinBase = ArchiPaletteColors.Apricot350.colorValue,
        dataEconomyCoinShadow = ArchiPaletteColors.ExtendedCoralTone58.colorValue,
        dataEconomyCoinHighlight = ArchiPaletteColors.ExtendedCoralTone96.colorValue,
        dataCollectionFoodPack = ArchiPaletteColors.Evergreen800.colorValue,
        dataCollectionCatPack = ArchiPaletteColors.Apricot800.colorValue,
        dataProgressDailyTotal = ArchiPaletteColors.Sage200.colorValue,
        dataProgressMealContribution = ArchiPaletteColors.Sage450.colorValue,
    ),
)

// FIGMA-TOKEN-INJECTION-POINT: type-scale
internal val DefaultDesignSystemStaticTypeScale = DesignSystemTypeScale(
    _displayRegularXXL = ArchiStaticTypeScale(
        fontFamily = juaDisplayFont,
        fontWeight = FontWeight.Normal,
        fontSize = 32,
        lineHeight = 40.0f,
        letterSpacing = 0.000f,
    ),
    _displayRegularXL = ArchiStaticTypeScale(
        fontFamily = juaDisplayFont,
        fontWeight = FontWeight.Normal,
        fontSize = 24,
        lineHeight = 32.0f,
        letterSpacing = 0.000f,
    ),
    _displayRegularL = ArchiStaticTypeScale(
        fontFamily = juaDisplayFont,
        fontWeight = FontWeight.Normal,
        fontSize = 20,
        lineHeight = 28.0f,
        letterSpacing = 0.000f,
    ),
    _displayRegularM = ArchiStaticTypeScale(
        fontFamily = juaDisplayFont,
        fontWeight = FontWeight.Normal,
        fontSize = 18,
        lineHeight = 26.0f,
        letterSpacing = 0.000f,
    ),
    _voiceRegularM = ArchiStaticTypeScale(
        fontFamily = gowunDodumVoiceFont,
        fontWeight = FontWeight.Normal,
        fontSize = 16,
        lineHeight = 24.0f,
        letterSpacing = 0.000f,
    ),
    _textStrongL = ArchiStaticTypeScale(
        fontFamily = notoSansKrTextFont,
        fontWeight = FontWeight.Medium,
        fontSize = 16,
        lineHeight = 24.0f,
        letterSpacing = 0.000f,
    ),
    _textRegularM = ArchiStaticTypeScale(
        fontFamily = notoSansKrTextFont,
        fontWeight = FontWeight.Normal,
        fontSize = 14,
        lineHeight = 22.0f,
        letterSpacing = 0.000f,
    ),
    _labelStrongS = ArchiStaticTypeScale(
        fontFamily = notoSansKrTextFont,
        fontWeight = FontWeight.Medium,
        fontSize = 12,
        lineHeight = 18.0f,
        letterSpacing = 0.000f,
    ),
    _numberStrongL = ArchiStaticTypeScale(
        fontFamily = fredokaNumberFont,
        fontWeight = FontWeight.Bold,
        fontSize = 24,
        lineHeight = 30.0f,
        letterSpacing = 0.000f,
    ),
    _labelRegularXS = ArchiStaticTypeScale(
        fontFamily = notoSansKrTextFont,
        fontWeight = FontWeight.Normal,
        fontSize = 11,
        lineHeight = 16.0f,
        letterSpacing = 0.000f,
    ),
    _labelStrongXS = ArchiStaticTypeScale(
        fontFamily = notoSansKrTextFont,
        fontWeight = FontWeight.Bold,
        fontSize = 11,
        lineHeight = 16.0f,
        letterSpacing = 0.000f,
    ),
    _textStrongM = ArchiStaticTypeScale(
        fontFamily = notoSansKrTextFont,
        fontWeight = FontWeight.Medium,
        fontSize = 14,
        lineHeight = 22.0f,
        letterSpacing = 0.000f,
    ),
    _textRegularS = ArchiStaticTypeScale(
        fontFamily = notoSansKrTextFont,
        fontWeight = FontWeight.Normal,
        fontSize = 12,
        lineHeight = 18.0f,
        letterSpacing = 0.000f,
    ),
    _titleStrongL = ArchiStaticTypeScale(
        fontFamily = juaDisplayFont,
        fontWeight = FontWeight.Normal,
        fontSize = 24,
        lineHeight = 32.0f,
        letterSpacing = 0.000f,
    ),
    _textRegularL = ArchiStaticTypeScale(
        fontFamily = notoSansKrTextFont,
        fontWeight = FontWeight.Normal,
        fontSize = 16,
        lineHeight = 24.0f,
        letterSpacing = 0.000f,
    ),
    _textRegularXS = ArchiStaticTypeScale(
        fontFamily = notoSansKrTextFont,
        fontWeight = FontWeight.Normal,
        fontSize = 11,
        lineHeight = 16.0f,
        letterSpacing = 0.000f,
    ),
    _displayStrongXL = ArchiStaticTypeScale(
        fontFamily = notoSansKrTextFont,
        fontWeight = FontWeight.Bold,
        fontSize = 26,
        lineHeight = 34.0f,
        letterSpacing = 0.000f,
    ),
    _textStrongXL = ArchiStaticTypeScale(
        fontFamily = notoSansKrTextFont,
        fontWeight = FontWeight.Bold,
        fontSize = 18,
        lineHeight = 26.0f,
        letterSpacing = 0.000f,
    ),
    _displayStrongL = ArchiStaticTypeScale(
        fontFamily = notoSansKrTextFont,
        fontWeight = FontWeight.Bold,
        fontSize = 22,
        lineHeight = 30.0f,
        letterSpacing = 0.000f,
    ),
    _displayStrongM = ArchiStaticTypeScale(
        fontFamily = notoSansKrTextFont,
        fontWeight = FontWeight.Bold,
        fontSize = 20,
        lineHeight = 28.0f,
        letterSpacing = 0.000f,
    ),
    _numberStrongM = ArchiStaticTypeScale(
        fontFamily = fredokaNumberFont,
        fontWeight = FontWeight.Bold,
        fontSize = 18,
        lineHeight = 24.0f,
        letterSpacing = 0.000f,
    ),
)

// DESIGN-TOKEN-SECTION: dimensions
internal val DefaultDesignSystemRadius = DesignSystemRadius(
    radius0 = 0.0.dp,
    radius8 = 8.0.dp,
    radius12 = 12.0.dp,
    radius16 = 16.0.dp,
    radius20 = 20.0.dp,
    radius24 = 24.0.dp,
    radius32 = 32.0.dp,
    radiusFull = 999.0.dp,
    radius22 = 22.0.dp,
)

internal val DefaultDesignSystemSpacing = DesignSystemSpacing(
    space4 = 4.0.dp,
    space8 = 8.0.dp,
    space12 = 12.0.dp,
    space16 = 16.0.dp,
    space20 = 20.0.dp,
    space24 = 24.0.dp,
    space32 = 32.0.dp,
)

internal val DefaultDesignSystemSize = DesignSystemSize(
    characterPixelMaster = 128.0.dp,
    characterHome = 152.0.dp,
    character3dHero = 224.0.dp,
    bottomNavigation = 76.0.dp,
    bottomNavigationCompact = 66.0.dp,
    bottomNavigationFloating = 76.0.dp,
    bottomNavigationFullWidth = 80.0.dp,
    calendarFoodIcon = 24.0.dp,
    calendarStatusMarker = 6.0.dp,
    minimumTouchTarget = 48.0.dp,
    mealRowMinHeight = 68.0.dp,
    mealLeadingIcon = 44.0.dp,
)

internal val DefaultDesignSystemLayout = DesignSystemLayout(
    mobileGutter = 20.0.dp,
)

// DESIGN-TOKEN-SECTION: shapes
internal val DefaultDesignSystemShape = DesignSystemShape(
    buttonDefault = RoundedCornerShape(DefaultDesignSystemRadius.radius12),
    inputDefault = RoundedCornerShape(DefaultDesignSystemRadius.radius12),
    calendarDay = RoundedCornerShape(DefaultDesignSystemRadius.radius12),
    cardDefault = RoundedCornerShape(DefaultDesignSystemRadius.radius16),
    coachBubble = RoundedCornerShape(DefaultDesignSystemRadius.radius16),
    dialogDefault = RoundedCornerShape(DefaultDesignSystemRadius.radius20),
    sheetDefault = RoundedCornerShape(DefaultDesignSystemRadius.radius24),
    navigationFloating = RoundedCornerShape(DefaultDesignSystemRadius.radius22),
    pill = RoundedCornerShape(DefaultDesignSystemRadius.radiusFull),
    progress = RoundedCornerShape(DefaultDesignSystemRadius.radiusFull),
    handle = RoundedCornerShape(DefaultDesignSystemRadius.radiusFull),
    toast = RoundedCornerShape(DefaultDesignSystemRadius.radius16),
)

// DESIGN-TOKEN-SECTION: elevation-effects
internal val DefaultDesignSystemElevation = DesignSystemElevation(
    navigationFloating = DesignSystemShadow(
        color = ArchiPaletteColors.ExtendedInkTone36Alpha18.colorValue,
        blurRadius = 16.0.dp,
        spreadRadius = 0.0.dp,
        offsetX = 0.0.dp,
        offsetY = -2.0.dp,
    ),
    surfaceLow = DesignSystemShadow(
        color = ArchiPaletteColors.ExtendedInkTone20Alpha6.colorValue,
        blurRadius = 12.0.dp,
        spreadRadius = 0.0.dp,
        offsetX = 0.0.dp,
        offsetY = 4.0.dp,
    ),
    dialogStandard = DesignSystemShadow(
        color = ArchiPaletteColors.ExtendedInkTone15Alpha14.colorValue,
        blurRadius = 28.0.dp,
        spreadRadius = 0.0.dp,
        offsetX = 0.0.dp,
        offsetY = 12.0.dp,
    ),
    sheetStandard = DesignSystemShadow(
        color = ArchiPaletteColors.ExtendedInkTone20Alpha13.colorValue,
        blurRadius = 24.0.dp,
        spreadRadius = 0.0.dp,
        offsetX = 0.0.dp,
        offsetY = -8.0.dp,
    ),
    floatingAction = DesignSystemShadow(
        color = ArchiPaletteColors.ExtendedEvergreenTone45Alpha18.colorValue,
        blurRadius = 14.0.dp,
        spreadRadius = 0.0.dp,
        offsetX = 0.0.dp,
        offsetY = 5.0.dp,
    ),
)

internal val DefaultDesignSystemEffects = DesignSystemEffects(
    modalBackgroundBlur = 2.0.dp,
)
